# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:

  strategy:
    matrix:
      node-version: [ 12.x, 15.x ]

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn
    - run: yarn lint
    - run: yarn test
    - run: yarn build --prod
    - run: yarn test --code-coverage
